CREATE SEQUENCE SPACE START WITH 1;

CREATE TABLE SPACE (
    ID INT NOT NULL,
    XLIMIT INT NOT NULL,
    YLIMIT INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE SPACECRAFT START WITH 1;

CREATE TABLE SPACECRAFT (
   ID INT NOT NULL,
   SPACE_ID INT NOT NULL,
   XPOSINIT INT NOT NULL,
   YPOSINIT INT NOT NULL,
   DIRECTIONINIT CHAR(1) NOT NULL,
   COMANDS VARCHAR(255) NOT NULL,
   XPOSLAST INT NOT NULL,
   YPOSLAST INT NOT NULL,
   DIRECTIONLAST CHAR(1) NOT NULL,
   PRIMARY KEY (ID)
);